dataset: cifar10

# arguments for C
c_model_name: cifar10_resnet_26
c_loss: mtdoublessl
c_step: ramp_swa
c_optim: nesterov
c_lr: 0.05
c_beta1: 0.9
c_beta2: 0.999
c_weight_decay: 0.0002

# Consistency hyperparameters
max_consistency_cost: 100.0
ema_decay_during_rampup: 0.97
ema_decay_after_rampup: 0.97
alpha_mse: 0.01

# Optimizer hyperparameters
lr_anneal_num: 999999999
lr_anneal_interval: 999999999
lr_anneal_coe: 0.995
# Training schedule
rampup_length: 2500
rampup_length_lr: 0
rampdown_length: 105000
swa_start: 90000
cycle_interval: 15000

# Preprocessing
zca: true
norm: false
translate: 4
flip_horizontal: true
ssl_seed: 1001

# training arguments:
n_iter: 1000000
batch_size: 128
clip_value: -1
save_every: 10000
n_labels: 4000
num_label_per_batch: 31
