dataset: SVHN

# arguments for D
c_model_name: cifar10_cnn

c_loss: entropyssl
c_optim: adam
c_lr: 0.0001
c_beta1: 0.
c_beta2: 0.99

# Consistency hyperparameters
max_consistency_cost: 50.0
ema_decay_during_rampup: 0.99
ema_decay_after_rampup: 0.999

# Optimizer hyperparameters
max_learning_rate: 0.003
adam_beta_1_before_rampdown: 0.9
adam_beta_1_after_rampdown: 0.5
adam_beta_2_during_rampup: 0.99
adam_beta_2_after_rampup: 0.999

# Training schedule
rampup_length: 40000
rampdown_length: 0

data_augment: data_augment_svhn.yaml
ssl_seed: 1

# training arguments:
n_iter: 150000
batch_size: 100
clip_value: -1
save_every: 1000
n_labels: 1000

