dataset: SVHN

# arguments for D
c_model_name: cifar10_cnn

c_loss: entropyssl
c_optim: adam
c_lr: 0.0001
c_beta1: 0.
c_beta2: 0.99
alpha_entropy: 0.3

data_augment: data_augment_cifar.yaml
ssl_seed: 1

# training arguments:
n_iter: 700000
batch_size: 100
clip_value: -1
save_every: 1000
n_labels: 1000
