dataset: svhn

# arguments for C
c_model_name: vat_cnn
topbn: true
c_loss: vatssl
c_optim: adam
c_lr: 0.001
c_beta1: 0.5
c_beta2: 0.999
c_step: step_vat

# Consistency hyperparameters
vat_eps: 2.5
lr_anneal_num: 32000
vat_xi: 0.000001
vat_iters: 1
ema_decay_after_rampup: 0.999ß

# Preprocessing
zca: false
norm: false
translate: 0
flip_horizontal: false
ssl_seed: 1

# training arguments:
n_iter: 48000
batch_size: 160
num_label_per_batch: 32
clip_value: -1
save_every: 10000
n_labels: 1000
