dataset: cifar10
key: unconditional

batch_size: 100
bs_g: 100
clip_value: -1
n_labels: 50000
ssl_seed: 1001
save_every: 2000
n_iter: 500000
n_iter_d: 5
gan_type: hinge
gan_traind_c: int
clc_reg: 0.

# arguments for G
g_model_name: resnet_sngan_un
g_z_dim: 256
g_embed_size: 256
g_nfilter: 32
g_nfilter_max: 256
g_actvn: relu

g_optim: adam
g_lr: 0.0001
g_beta1: 0.
g_beta2: 0.99

# arguments for D
d_model_name: resnet_sngan_un
d_z_dim: 256
d_embed_size: 256
d_nfilter: 32
d_nfilter_max: 256
d_actvn: relu

d_optim: adam
d_lr: 0.0001
d_beta1: 0.
d_beta2: 0.99
