dataset: SVHN

# training arguments:
n_iter: 700000
batch_size: 200
bs_g: 200
bs_c: 200
bs_c_for_d: 200
bs_l_for_d: 20
bs_u_for_d: 180
clip_value: -1
save_every: 10000
gan_type: hinge
gan_traind_c: int
clc_reg: 5

# arguments for C
c_model_name: cifar10_cnn

c_loss: mtssl
c_step: ramp
c_optim: adam
c_lr: 0.003
c_beta1: 0.5
c_beta2: 0.999
alpha_c_adv: 0.01
alpha_c_pdl: 0.03
psl_iters: 150000

# Lr schdule:
lr_anneal_num: 1000000
lr_anneal_interval: 500
lr_anneal_coe: 1
# Consistency hyperparameters
max_consistency_cost: 50.0
ema_decay_during_rampup: 0.99
ema_decay_after_rampup: 0.999
# Optimizer hyperparameters
adam_beta_1_before_rampdown: 0.9
adam_beta_1_after_rampdown: 0.5
adam_beta_2_during_rampup: 0.99
adam_beta_2_after_rampup: 0.999
# Training schedule
rampup_length: 40000
rampup_length_lr: 40000
rampdown_length: 0

# Preprocessing
zca: false
norm: false
translate: 0
flip_horizontal: false
ssl_seed: 1

# arguments for G
g_model_name: Resnet_RegGAN
g_z_dim: 256
g_embed_size: 256
g_nfilter: 32
g_nfilter_max: 256
g_actvn: relu

g_optim: adam
g_lr: 0.0001
g_beta1: 0.
g_beta2: 0.99

# arguments for D
d_model_name: Resnet_RegGAN
d_z_dim: 256
d_embed_size: 256
d_nfilter: 32
d_nfilter_max: 256
d_actvn: relu

d_optim: adam
d_lr: 0.0001
d_beta1: 0.
d_beta2: 0.99
